# name: Build Django Application

# on:
#   push:
#     branches: ['master']
#   pull_request:
#     branches: [ "master" ]

# jobs:
#     test_django_job:
#       uses: joelwembo/django-multitenant-saas-ecommerce-kubernetes/.github/workflows/test-django.yaml@master
#     build:
#       runs-on: ubuntu-latest
#       needs: [test_django_job]

#     build-and-push-docker-image:
#       name: Build Docker image and push to repositories
#       # run only when code is compiling and tests are passing
#       runs-on: ubuntu-latest
#       # steps to perform in job
#       steps:
#         - name: Checkout code
#           uses: actions/checkout@v3

#         # setup Docker buld action
#         - name: Set up Docker Buildx
#           id: buildx
#           uses: docker/setup-buildx-action@v2

#         - name: Login to DockerHub
#           uses: docker/login-action@v2
#           with:
#             username: ${{ secrets.DOCKER_USER }}
#             password: ${{ secrets.DOCKER_PASSWORD }}

#         - name: Login to Github Packages
#           uses: docker/login-action@v2
#           with:
#             registry: ghcr.io
#             username: ${{ github.actor }}
#             password: ${{ secrets.G_TOKEN }}

#         - name: Build image and push to Docker Hub and GitHub Container Registry
#           uses: docker/build-push-action@v2
#           with:
#             # relative path to the place where source code with Dockerfile is located
#             context: ./
#             # Note: tags has to be all lower-case
#             tags: |
#               joelwembo/cloudapp-django-web:${{ github.sha }}
#               ghcr.io/joelwembo/cloudapp-django-web:${{ github.sha }}
#             # build on feature branches, push only on main branch
#             push: ${{ github.ref == 'refs/heads/master' }}



